### ISSUE TITLE
Cannot migrate from rest to nessie

### ISSUE THREAD

**Issue by tamarinkeisari** [projectnessie/iceberg-catalog-migrator#186]
Hi I am trying to migrate from rest to nessie but I am getting unable to load AWS credentials although I put the environment variables of AWS 

can you show an example for migrating from rest to nessie

**Comment by snazy** [comment]
@tamarinkeisari we use github issues for code related stuff.
Mind heading over to our [Zulip chat](https://project-nessie.zulipchat.com/) and ask there?
